# R packages used in the project
library(base)
library(car)
library(caret)
library(datasets)
library(devtools)
library(doMC)
library(dplyr)
library(ggplot2)
library(graphics)
library(grDevices)
library(iterators)
library(knitr)
library(parallel)
library(pls)
library(rmarkdown)
library(utils)
library(xtable)
library(glmnet)

sink("../../session-info.txt")
system("git --version")
system("latex --version")
system("pandoc --version")
system("Make --version")


cat("Session Information\n")
print(sessionInfo())
print(devtools::session_info(), "\n")
sink()
